/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2025-04-19 10:16:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class appointmentList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1744694913000L));
    _jspx_dependants.put("jar:file:/Users/dipaktolangi/Desktop/Coursework%202/Health/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HealthCare/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602853272000L));
    _jspx_dependants.put("jar:file:/Users/dipaktolangi/Desktop/Coursework%202/Health/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HealthCare/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fmt.tld", Long.valueOf(1602853272000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>Appointment Management</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&family=Inter:wght@400;500;600&display=swap\" rel=\"stylesheet\">\n");
      out.write("<style>\n");
      out.write(":root {\n");
      out.write("    --primary: #7c3aed;\n");
      out.write("    --primary-light: #8b5cf6;\n");
      out.write("    --primary-dark: #6d28d9;\n");
      out.write("    --secondary: #10b981;\n");
      out.write("    --accent: #f59e0b;\n");
      out.write("    --danger: #ef4444;\n");
      out.write("    --info: #0ea5e9;\n");
      out.write("    \n");
      out.write("    --bg-dark: #0f172a;\n");
      out.write("    --bg-darker: #020617;\n");
      out.write("    --bg-card: #1e293b;\n");
      out.write("    --text-primary: #f8fafc;\n");
      out.write("    --text-secondary: #94a3b8;\n");
      out.write("    --border-color: #334155;\n");
      out.write("    --highlight: rgba(124, 58, 237, 0.1);\n");
      out.write("    \n");
      out.write("    --sidebar-width: 280px;\n");
      out.write("    --nav-height: 80px;\n");
      out.write("    --card-radius: 16px;\n");
      out.write("    --transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);\n");
      out.write("}\n");
      out.write("\n");
      out.write("* {\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    font-family: 'Inter', 'Poppins', -apple-system, BlinkMacSystemFont, sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("    background-color: var(--bg-dark);\n");
      out.write("    color: var(--text-primary);\n");
      out.write("    line-height: 1.6;\n");
      out.write("    overflow-x: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dashboard-container {\n");
      out.write("    display: flex;\n");
      out.write("    flex-direction: column;\n");
      out.write("    min-height: 100vh;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Top Navigation */\n");
      out.write(".top-nav {\n");
      out.write("    background: var(--bg-darker);\n");
      out.write("    padding: 0 2rem;\n");
      out.write("    position: sticky;\n");
      out.write("    top: 0;\n");
      out.write("    z-index: 1000;\n");
      out.write("    border-bottom: 1px solid var(--border-color);\n");
      out.write("    box-shadow: 0 1px 3px rgba(0,0,0,0.1);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-container {\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: space-between;\n");
      out.write("    align-items: center;\n");
      out.write("    height: var(--nav-height);\n");
      out.write("    max-width: 1800px;\n");
      out.write("    margin: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".brand {\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    gap: 14px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".brand-logo {\n");
      out.write("    font-size: 1.6rem;\n");
      out.write("    font-weight: 700;\n");
      out.write("    color: var(--text-primary);\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    gap: 10px;\n");
      out.write("    letter-spacing: -0.5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".brand-logo i {\n");
      out.write("    color: var(--primary-light);\n");
      out.write("    font-size: 1.8rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mobile-menu-btn {\n");
      out.write("    display: none;\n");
      out.write("    background: none;\n");
      out.write("    border: none;\n");
      out.write("    color: var(--text-primary);\n");
      out.write("    font-size: 1.6rem;\n");
      out.write("    cursor: pointer;\n");
      out.write("    transition: var(--transition);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mobile-menu-btn:hover {\n");
      out.write("    color: var(--primary-light);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-menu {\n");
      out.write("    display: flex;\n");
      out.write("    list-style: none;\n");
      out.write("    gap: 1.5rem;\n");
      out.write("    margin-left: 3rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link {\n");
      out.write("    color: var(--text-secondary);\n");
      out.write("    text-decoration: none;\n");
      out.write("    padding: 0.75rem 1rem;\n");
      out.write("    border-radius: var(--card-radius);\n");
      out.write("    transition: var(--transition);\n");
      out.write("    font-weight: 500;\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    gap: 10px;\n");
      out.write("    font-size: 0.95rem;\n");
      out.write("    position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link i {\n");
      out.write("    font-size: 1.1rem;\n");
      out.write("    width: 24px;\n");
      out.write("    text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link:hover, .nav-link.active {\n");
      out.write("    color: var(--primary-light);\n");
      out.write("    background-color: var(--highlight);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link.active::after {\n");
      out.write("    content: '';\n");
      out.write("    position: absolute;\n");
      out.write("    bottom: -12px;\n");
      out.write("    left: 50%;\n");
      out.write("    transform: translateX(-50%);\n");
      out.write("    width: 6px;\n");
      out.write("    height: 6px;\n");
      out.write("    border-radius: 50%;\n");
      out.write("    background-color: var(--primary-light);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".user-actions {\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    gap: 1.5rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".user-info {\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    gap: 12px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".user-avatar {\n");
      out.write("    width: 44px;\n");
      out.write("    height: 44px;\n");
      out.write("    border-radius: 50%;\n");
      out.write("    background: linear-gradient(135deg, var(--primary), var(--info));\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    justify-content: center;\n");
      out.write("    font-weight: bold;\n");
      out.write("    color: white;\n");
      out.write("    font-size: 1.1rem;\n");
      out.write("    transition: var(--transition);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".user-info:hover .user-avatar {\n");
      out.write("    transform: scale(1.05);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".user-name {\n");
      out.write("    font-weight: 600;\n");
      out.write("    max-width: 140px;\n");
      out.write("    white-space: nowrap;\n");
      out.write("    overflow: hidden;\n");
      out.write("    text-overflow: ellipsis;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".user-dropdown {\n");
      out.write("    position: absolute;\n");
      out.write("    top: 120%;\n");
      out.write("    right: 0;\n");
      out.write("    background: var(--bg-card);\n");
      out.write("    border-radius: var(--card-radius);\n");
      out.write("    box-shadow: 0 10px 15px -3px rgba(0,0,0,0.2);\n");
      out.write("    padding: 0.75rem 0;\n");
      out.write("    min-width: 220px;\n");
      out.write("    z-index: 100;\n");
      out.write("    opacity: 0;\n");
      out.write("    visibility: hidden;\n");
      out.write("    transform: translateY(10px);\n");
      out.write("    transition: var(--transition);\n");
      out.write("    border: 1px solid var(--border-color);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".user-info:hover .user-dropdown {\n");
      out.write("    opacity: 1;\n");
      out.write("    visibility: visible;\n");
      out.write("    transform: translateY(0);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".user-dropdown-link {\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    gap: 12px;\n");
      out.write("    padding: 0.85rem 1.5rem;\n");
      out.write("    color: var(--text-primary);\n");
      out.write("    text-decoration: none;\n");
      out.write("    transition: var(--transition);\n");
      out.write("    font-size: 0.95rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".user-dropdown-link:hover {\n");
      out.write("    background-color: rgba(255,255,255,0.05);\n");
      out.write("    color: var(--primary-light);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".user-dropdown-link i {\n");
      out.write("    width: 20px;\n");
      out.write("    color: var(--text-secondary);\n");
      out.write("    font-size: 1rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logout-btn {\n");
      out.write("    background-color: var(--danger);\n");
      out.write("    color: white;\n");
      out.write("    border: none;\n");
      out.write("    padding: 0.75rem 1.5rem;\n");
      out.write("    border-radius: var(--card-radius);\n");
      out.write("    cursor: pointer;\n");
      out.write("    font-weight: 600;\n");
      out.write("    transition: var(--transition);\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    gap: 10px;\n");
      out.write("    font-size: 0.95rem;\n");
      out.write("    box-shadow: 0 4px 6px -1px rgba(239, 68, 68, 0.2);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logout-btn:hover {\n");
      out.write("    background-color: #dc2626;\n");
      out.write("    transform: translateY(-2px);\n");
      out.write("    box-shadow: 0 10px 15px -3px rgba(239, 68, 68, 0.2);\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Main Content */\n");
      out.write(".main-content {\n");
      out.write("    flex: 1;\n");
      out.write("    padding: 2.5rem;\n");
      out.write("    max-width: 1800px;\n");
      out.write("    margin: 0 auto;\n");
      out.write("    width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".page-header {\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: space-between;\n");
      out.write("    align-items: center;\n");
      out.write("    margin-bottom: 3rem;\n");
      out.write("    flex-wrap: wrap;\n");
      out.write("    gap: 1.5rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".page-title {\n");
      out.write("    font-size: 2rem;\n");
      out.write("    font-weight: 700;\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    gap: 14px;\n");
      out.write("    letter-spacing: -0.5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".page-title i {\n");
      out.write("    color: var(--primary-light);\n");
      out.write("    font-size: 2.2rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".breadcrumb {\n");
      out.write("    font-size: 0.95rem;\n");
      out.write("    color: var(--text-secondary);\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    gap: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".breadcrumb a {\n");
      out.write("    color: var(--text-secondary);\n");
      out.write("    text-decoration: none;\n");
      out.write("    transition: var(--transition);\n");
      out.write("    font-weight: 500;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".breadcrumb a:hover {\n");
      out.write("    color: var(--primary-light);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".breadcrumb .separator {\n");
      out.write("    opacity: 0.5;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Appointment Table */\n");
      out.write(".appointment-table-container {\n");
      out.write("    background-color: var(--bg-card);\n");
      out.write("    border-radius: var(--card-radius);\n");
      out.write("    padding: 2rem;\n");
      out.write("    border: 1px solid var(--border-color);\n");
      out.write("    margin-bottom: 3rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".appointment-table {\n");
      out.write("    width: 100%;\n");
      out.write("    border-collapse: collapse;\n");
      out.write("    margin-top: 1.5rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".appointment-table th, .appointment-table td {\n");
      out.write("    padding: 1rem 1.5rem;\n");
      out.write("    text-align: left;\n");
      out.write("    border-bottom: 1px solid var(--border-color);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".appointment-table th {\n");
      out.write("    color: var(--text-secondary);\n");
      out.write("    font-weight: 600;\n");
      out.write("    text-transform: uppercase;\n");
      out.write("    font-size: 0.85rem;\n");
      out.write("    letter-spacing: 0.5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".appointment-table tr:last-child td {\n");
      out.write("    border-bottom: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".appointment-table tr:hover {\n");
      out.write("    background-color: rgba(255,255,255,0.03);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".status-badge {\n");
      out.write("    display: inline-block;\n");
      out.write("    padding: 0.35rem 0.75rem;\n");
      out.write("    border-radius: 20px;\n");
      out.write("    font-size: 0.85rem;\n");
      out.write("    font-weight: 600;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".status-scheduled {\n");
      out.write("    background-color: rgba(243, 156, 18, 0.1);\n");
      out.write("    color: var(--accent);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".status-completed {\n");
      out.write("    background-color: rgba(16, 185, 129, 0.1);\n");
      out.write("    color: var(--secondary);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".status-cancelled {\n");
      out.write("    background-color: rgba(239, 68, 68, 0.1);\n");
      out.write("    color: var(--danger);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".action-btn {\n");
      out.write("    padding: 0.5rem 1rem;\n");
      out.write("    border: none;\n");
      out.write("    border-radius: var(--card-radius);\n");
      out.write("    cursor: pointer;\n");
      out.write("    text-decoration: none;\n");
      out.write("    font-size: 0.85rem;\n");
      out.write("    font-weight: 600;\n");
      out.write("    margin-right: 0.5rem;\n");
      out.write("    transition: var(--transition);\n");
      out.write("    display: inline-flex;\n");
      out.write("    align-items: center;\n");
      out.write("    gap: 6px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".action-btn i {\n");
      out.write("    font-size: 0.8rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-btn {\n");
      out.write("    background-color: rgba(16, 185, 129, 0.1);\n");
      out.write("    color: var(--secondary);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-btn:hover {\n");
      out.write("    background-color: var(--secondary);\n");
      out.write("    color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".cancel-btn {\n");
      out.write("    background-color: rgba(239, 68, 68, 0.1);\n");
      out.write("    color: var(--danger);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".cancel-btn:hover {\n");
      out.write("    background-color: var(--danger);\n");
      out.write("    color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".add-btn {\n");
      out.write("    display: inline-flex;\n");
      out.write("    align-items: center;\n");
      out.write("    gap: 8px;\n");
      out.write("    padding: 0.75rem 1.5rem;\n");
      out.write("    background-color: var(--primary);\n");
      out.write("    color: white;\n");
      out.write("    text-decoration: none;\n");
      out.write("    border-radius: var(--card-radius);\n");
      out.write("    margin-bottom: 1.5rem;\n");
      out.write("    font-weight: 600;\n");
      out.write("    transition: var(--transition);\n");
      out.write("    box-shadow: 0 4px 6px -1px rgba(124, 58, 237, 0.2);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".add-btn:hover {\n");
      out.write("    background-color: var(--primary-dark);\n");
      out.write("    transform: translateY(-2px);\n");
      out.write("    box-shadow: 0 10px 15px -3px rgba(124, 58, 237, 0.3);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".add-btn i {\n");
      out.write("    font-size: 0.9rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Footer */\n");
      out.write(".footer {\n");
      out.write("    background-color: var(--bg-darker);\n");
      out.write("    color: var(--text-secondary);\n");
      out.write("    padding: 2rem;\n");
      out.write("    text-align: center;\n");
      out.write("    border-top: 1px solid var(--border-color);\n");
      out.write("    margin-top: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-content {\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: space-between;\n");
      out.write("    align-items: center;\n");
      out.write("    max-width: 1800px;\n");
      out.write("    margin: 0 auto;\n");
      out.write("    flex-wrap: wrap;\n");
      out.write("    gap: 1.5rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-links {\n");
      out.write("    display: flex;\n");
      out.write("    gap: 1.5rem;\n");
      out.write("    flex-wrap: wrap;\n");
      out.write("    justify-content: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-link {\n");
      out.write("    color: var(--text-secondary);\n");
      out.write("    text-decoration: none;\n");
      out.write("    transition: var(--transition);\n");
      out.write("    font-size: 0.9rem;\n");
      out.write("    font-weight: 500;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-link:hover {\n");
      out.write("    color: var(--primary-light);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".copyright {\n");
      out.write("    color: var(--text-secondary);\n");
      out.write("    font-size: 0.9rem;\n");
      out.write("    font-weight: 500;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Responsive adjustments */\n");
      out.write("@media (max-width: 1200px) {\n");
      out.write("    .nav-menu {\n");
      out.write("        gap: 1rem;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media (max-width: 992px) {\n");
      out.write("    .mobile-menu-btn {\n");
      out.write("        display: block;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .nav-menu {\n");
      out.write("        position: fixed;\n");
      out.write("        top: var(--nav-height);\n");
      out.write("        left: -100%;\n");
      out.write("        width: 300px;\n");
      out.write("        height: calc(100vh - var(--nav-height));\n");
      out.write("        background: var(--bg-darker);\n");
      out.write("        flex-direction: column;\n");
      out.write("        gap: 0;\n");
      out.write("        padding: 2rem 0;\n");
      out.write("        transition: var(--transition);\n");
      out.write("        z-index: 999;\n");
      out.write("        overflow-y: auto;\n");
      out.write("        box-shadow: 0 20px 25px -5px rgba(0,0,0,0.1);\n");
      out.write("        border-right: 1px solid var(--border-color);\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .nav-menu.active {\n");
      out.write("        left: 0;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .nav-link {\n");
      out.write("        padding: 1rem 2rem;\n");
      out.write("        border-radius: 0;\n");
      out.write("        border-left: 4px solid transparent;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .nav-link.active {\n");
      out.write("        border-left-color: var(--primary);\n");
      out.write("        background-color: var(--highlight);\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .nav-link.active::after {\n");
      out.write("        display: none;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .user-actions {\n");
      out.write("        margin-left: auto;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media (max-width: 768px) {\n");
      out.write("    .top-nav {\n");
      out.write("        padding: 0 1.5rem;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .brand-logo {\n");
      out.write("        font-size: 1.4rem;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .page-header {\n");
      out.write("        flex-direction: column;\n");
      out.write("        align-items: flex-start;\n");
      out.write("        margin-bottom: 2rem;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .page-title {\n");
      out.write("        font-size: 1.8rem;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .main-content {\n");
      out.write("        padding: 1.5rem;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .user-name {\n");
      out.write("        display: none;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .footer-content {\n");
      out.write("        flex-direction: column;\n");
      out.write("        gap: 1rem;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .appointment-table-container {\n");
      out.write("        padding: 1.5rem;\n");
      out.write("        overflow-x: auto;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media (max-width: 576px) {\n");
      out.write("    .top-nav {\n");
      out.write("        padding: 0 1rem;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .logout-btn span {\n");
      out.write("        display: none;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .logout-btn {\n");
      out.write("        padding: 0.75rem;\n");
      out.write("        width: 48px;\n");
      out.write("        height: 48px;\n");
      out.write("        justify-content: center;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .appointment-table th, \n");
      out.write("    .appointment-table td {\n");
      out.write("        padding: 0.75rem;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"dashboard-container\">\n");
      out.write("        <!-- Top Navigation -->\n");
      out.write("        <nav class=\"top-nav\">\n");
      out.write("            <div class=\"nav-container\">\n");
      out.write("                <div class=\"brand\">\n");
      out.write("                    <button class=\"mobile-menu-btn\" id=\"mobileMenuBtn\">\n");
      out.write("                        <i class=\"fas fa-bars\"></i>\n");
      out.write("                    </button>\n");
      out.write("                    <span class=\"brand-logo\">\n");
      out.write("                        <i class=\"fas fa-heart-pulse\"></i> HealthCare\n");
      out.write("                    </span>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <ul class=\"nav-menu\" id=\"navMenu\">\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/DashboardServlet\" class=\"nav-link\">\n");
      out.write("                            <i class=\"fas fa-chart-line\"></i>\n");
      out.write("                            <span>Dashboard</span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/DoctorListServlet\" class=\"nav-link\">\n");
      out.write("                            <i class=\"fas fa-user-md\"></i>\n");
      out.write("                            <span>Doctors</span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/PatientListServlet\" class=\"nav-link\">\n");
      out.write("                            <i class=\"fas fa-procedures\"></i>\n");
      out.write("                            <span>Patients</span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AppointmentListServlet\" class=\"nav-link active\">\n");
      out.write("                            <i class=\"fas fa-calendar-check\"></i>\n");
      out.write("                            <span>Appointments</span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/MedicalRecordListServlet\" class=\"nav-link\">\n");
      out.write("                            <i class=\"fas fa-file-waveform\"></i>\n");
      out.write("                            <span>Medical Records</span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                \n");
      out.write("                <div class=\"user-actions\">\n");
      out.write("                    <div class=\"user-info\">\n");
      out.write("                        <div class=\"user-avatar\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.username.charAt(0)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("                        <span class=\"user-name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.username}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("                        <div class=\"user-dropdown\">\n");
      out.write("                            <a href=\"#\" class=\"user-dropdown-link\">\n");
      out.write("                                <i class=\"fas fa-user-circle\"></i> My Profile\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/UserSettingsServlet\" class=\"user-dropdown-link\">\n");
      out.write("                                <i class=\"fas fa-cog\"></i> Settings\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"#\" class=\"user-dropdown-link\">\n");
      out.write("                                <i class=\"fas fa-bell\"></i> Notifications\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\" method=\"post\">\n");
      out.write("                        <button type=\"submit\" class=\"logout-btn\">\n");
      out.write("                            <i class=\"fas fa-sign-out-alt\"></i>\n");
      out.write("                            <span>Logout</span>\n");
      out.write("                        </button>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("\n");
      out.write("        <!-- Main Content -->\n");
      out.write("        <main class=\"main-content\">\n");
      out.write("            <div class=\"page-header\">\n");
      out.write("                <h1 class=\"page-title\">\n");
      out.write("                    <i class=\"fas fa-calendar-check\"></i> Appointment Management\n");
      out.write("                </h1>\n");
      out.write("                <div class=\"breadcrumb\">\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/DashboardServlet\">Home</a> \n");
      out.write("                    <span class=\"separator\">/</span> \n");
      out.write("                    <span>Appointments</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LoadAppointmentFormDataServlet\" class=\"add-btn\">\n");
      out.write("                <i class=\"fas fa-plus\"></i> Schedule New Appointment\n");
      out.write("            </a>\n");
      out.write("            \n");
      out.write("            <div class=\"appointment-table-container\">\n");
      out.write("                <table class=\"appointment-table\">\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>ID</th>\n");
      out.write("                            <th>Date</th>\n");
      out.write("                            <th>Time</th>\n");
      out.write("                            <th>Patient</th>\n");
      out.write("                            <th>Doctor</th>\n");
      out.write("                            <th>Status</th>\n");
      out.write("                            <th>Actions</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </main>\n");
      out.write("\n");
      out.write("        <!-- Footer -->\n");
      out.write("        <footer class=\"footer\">\n");
      out.write("            <div class=\"footer-content\">\n");
      out.write("                <div class=\"footer-links\">\n");
      out.write("                    <a href=\"#\" class=\"footer-link\">About</a>\n");
      out.write("                    <a href=\"#\" class=\"footer-link\">Privacy</a>\n");
      out.write("                    <a href=\"#\" class=\"footer-link\">Terms</a>\n");
      out.write("                    <a href=\"#\" class=\"footer-link\">Contact</a>\n");
      out.write("                    <a href=\"#\" class=\"footer-link\">Support</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"copyright\">\n");
      out.write("                    &copy; 2023 MedAdmin Pro. All rights reserved.\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /view/appointmentList.jsp(706,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("appointment");
      // /view/appointmentList.jsp(706,24) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/view/appointmentList.jsp(706,24) '${appointments}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${appointments}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                            <tr>\n");
            out.write("                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.appointmentId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                <td>");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\n");
            out.write("                                <td>");
            if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\n");
            out.write("                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.patientName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                <td>Dr. ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.doctorName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                <td>\n");
            out.write("                                    <span class=\"status-badge status-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.status.toLowerCase()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("                                        ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.status}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\n");
            out.write("                                    </span>\n");
            out.write("                                </td>\n");
            out.write("                                <td>\n");
            out.write("                                    ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("                                </td>\n");
            out.write("                            </tr>\n");
            out.write("                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /view/appointmentList.jsp(709,36) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.date}", java.util.Date.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /view/appointmentList.jsp(709,36) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /view/appointmentList.jsp(710,36) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.time}", java.util.Date.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /view/appointmentList.jsp(710,36) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setPattern("HH:mm");
      int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
      _jspx_th_fmt_005fformatDate_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /view/appointmentList.jsp(719,36) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.status == 'SCHEDULED'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                        <a href=\"#\" class=\"action-btn edit-btn\">\n");
          out.write("                                            <i class=\"fas fa-edit\"></i> Edit\n");
          out.write("                                        </a>\n");
          out.write("                                        <a href=\"#\" class=\"action-btn cancel-btn\">\n");
          out.write("                                            <i class=\"fas fa-times\"></i> Cancel\n");
          out.write("                                        </a>\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
