/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2025-04-21 16:32:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class doctorAppointments_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1744694913000L));
    _jspx_dependants.put("jar:file:/Users/dipaktolangi/Desktop/Coursework%202/Health/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HealthCare/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602853272000L));
    _jspx_dependants.put("jar:file:/Users/dipaktolangi/Desktop/Coursework%202/Health/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HealthCare/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fmt.tld", Long.valueOf(1602853272000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>My Appointments</title>\n");
      out.write("<style>\n");
      out.write(":root {\n");
      out.write("	--primary-color: #6c5ce7;\n");
      out.write("	--secondary-color: #a29bfe;\n");
      out.write("	--accent-color: #fd79a8;\n");
      out.write("	--success-color: #00b894;\n");
      out.write("	--warning-color: #fdcb6e;\n");
      out.write("	--danger-color: #d63031;\n");
      out.write("	--info-color: #0984e3;\n");
      out.write("	--dark-color: #2d3436;\n");
      out.write("	--darker-color: #1e272e;\n");
      out.write("	--light-color: #f5f6fa;\n");
      out.write("	--text-color: #dfe6e9;\n");
      out.write("	--sidebar-bg: #1a1a2e;\n");
      out.write("	--card-bg: #16213e;\n");
      out.write("	--header-bg: #0f3460;\n");
      out.write("	--footer-bg: #1a1a2e;\n");
      out.write("}\n");
      out.write("\n");
      out.write("* {\n");
      out.write("	margin: 0;\n");
      out.write("	padding: 0;\n");
      out.write("	box-sizing: border-box;\n");
      out.write("	font-family: 'Poppins', -apple-system, BlinkMacSystemFont, 'Segoe UI',\n");
      out.write("		Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue',\n");
      out.write("		sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("	background-color: var(--darker-color);\n");
      out.write("	color: var(--text-color);\n");
      out.write("	line-height: 1.6;\n");
      out.write("	min-height: 100vh;\n");
      out.write("	display: flex;\n");
      out.write("	flex-direction: column;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Header Styles */\n");
      out.write(".header {\n");
      out.write("	background: linear-gradient(135deg, var(--header-bg) 0%,\n");
      out.write("		var(--dark-color) 100%);\n");
      out.write("	padding: 1rem 2rem;\n");
      out.write("	display: flex;\n");
      out.write("	justify-content: space-between;\n");
      out.write("	align-items: center;\n");
      out.write("	box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);\n");
      out.write("	position: sticky;\n");
      out.write("	top: 0;\n");
      out.write("	z-index: 100;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".header-title {\n");
      out.write("	font-size: 1.5rem;\n");
      out.write("	font-weight: 600;\n");
      out.write("	color: white;\n");
      out.write("	display: flex;\n");
      out.write("	align-items: center;\n");
      out.write("	gap: 0.5rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".header-title::before {\n");
      out.write("	content: \"⚕️\";\n");
      out.write("}\n");
      out.write("\n");
      out.write(".user-info {\n");
      out.write("	display: flex;\n");
      out.write("	align-items: center;\n");
      out.write("	gap: 1rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".user-greeting {\n");
      out.write("	font-size: 0.9rem;\n");
      out.write("	color: var(--secondary-color);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".username {\n");
      out.write("	font-weight: 600;\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Navigation Bar */\n");
      out.write(".nav-bar {\n");
      out.write("	background-color: rgba(0, 0, 0, 0.2);\n");
      out.write("	padding: 0.5rem 2rem;\n");
      out.write("	display: flex;\n");
      out.write("	gap: 1rem;\n");
      out.write("	border-bottom: 1px solid rgba(255, 255, 255, 0.1);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link {\n");
      out.write("	padding: 0.5rem 1rem;\n");
      out.write("	color: var(--text-color);\n");
      out.write("	text-decoration: none;\n");
      out.write("	border-radius: 4px;\n");
      out.write("	font-size: 0.9rem;\n");
      out.write("	transition: all 0.3s ease;\n");
      out.write("	display: flex;\n");
      out.write("	align-items: center;\n");
      out.write("	gap: 0.5rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link:hover {\n");
      out.write("	background-color: rgba(255, 255, 255, 0.1);\n");
      out.write("	transform: translateY(-2px);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link.active {\n");
      out.write("	background-color: var(--primary-color);\n");
      out.write("	color: white;\n");
      out.write("	box-shadow: 0 4px 8px rgba(108, 92, 231, 0.3);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link::before {\n");
      out.write("	font-size: 1.1rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link[href*=\"Dashboard\"]::before {\n");
      out.write("	content: \"📊\";\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link[href*=\"Appointments\"]::before {\n");
      out.write("	content: \"📅\";\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link[href*=\"Records\"]::before {\n");
      out.write("	content: \"📋\";\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link[href*=\"Schedule\"]::before {\n");
      out.write("	content: \"⏰\";\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link[href*=\"Settings\"]::before {\n");
      out.write("	content: \"⚙️\";\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Main Content */\n");
      out.write(".main-container {\n");
      out.write("	display: flex;\n");
      out.write("	flex: 1;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".sidebar {\n");
      out.write("	width: 250px;\n");
      out.write("	background-color: var(--sidebar-bg);\n");
      out.write("	padding: 1.5rem 0;\n");
      out.write("	border-right: 1px solid rgba(255, 255, 255, 0.1);\n");
      out.write("	display: flex;\n");
      out.write("	flex-direction: column;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".sidebar-header {\n");
      out.write("	padding: 0 1.5rem 1.5rem;\n");
      out.write("	border-bottom: 1px solid rgba(255, 255, 255, 0.1);\n");
      out.write("	margin-bottom: 1rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".sidebar-title {\n");
      out.write("	font-size: 1.2rem;\n");
      out.write("	color: var(--secondary-color);\n");
      out.write("	font-weight: 600;\n");
      out.write("	display: flex;\n");
      out.write("	align-items: center;\n");
      out.write("	gap: 0.5rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".sidebar-title::before {\n");
      out.write("	content: \"👨‍⚕️\";\n");
      out.write("}\n");
      out.write("\n");
      out.write(".quick-stats {\n");
      out.write("	padding: 1rem 1.5rem;\n");
      out.write("	margin-bottom: 1rem;\n");
      out.write("	background-color: rgba(0, 0, 0, 0.2);\n");
      out.write("	border-radius: 8px;\n");
      out.write("	margin: 0 1rem 1rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".stat-item {\n");
      out.write("	display: flex;\n");
      out.write("	justify-content: space-between;\n");
      out.write("	margin-bottom: 0.5rem;\n");
      out.write("	font-size: 0.9rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".stat-value {\n");
      out.write("	font-weight: 600;\n");
      out.write("	color: var(--accent-color);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main-content {\n");
      out.write("	flex: 1;\n");
      out.write("	padding: 2rem;\n");
      out.write("	background-color: var(--darker-color);\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Cards */\n");
      out.write(".card {\n");
      out.write("	background-color: var(--card-bg);\n");
      out.write("	border-radius: 12px;\n");
      out.write("	padding: 1.5rem;\n");
      out.write("	box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);\n");
      out.write("	margin-bottom: 2rem;\n");
      out.write("	border: 1px solid rgba(255, 255, 255, 0.05);\n");
      out.write("	transition: transform 0.3s ease, box-shadow 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card:hover {\n");
      out.write("	transform: translateY(-5px);\n");
      out.write("	box-shadow: 0 12px 24px rgba(0, 0, 0, 0.3);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card-header {\n");
      out.write("	display: flex;\n");
      out.write("	justify-content: space-between;\n");
      out.write("	align-items: center;\n");
      out.write("	margin-bottom: 1.5rem;\n");
      out.write("	padding-bottom: 1rem;\n");
      out.write("	border-bottom: 1px solid rgba(255, 255, 255, 0.1);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card-title {\n");
      out.write("	font-size: 1.3rem;\n");
      out.write("	color: var(--secondary-color);\n");
      out.write("	font-weight: 600;\n");
      out.write("	display: flex;\n");
      out.write("	align-items: center;\n");
      out.write("	gap: 0.5rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card-title::before {\n");
      out.write("	font-size: 1.1rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".appointments-card .card-title::before {\n");
      out.write("	content: \"🩺\";\n");
      out.write("}\n");
      out.write("\n");
      out.write(".pending-appointments-card .card-title::before {\n");
      out.write("	content: \"⏳\";\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Table Styles */\n");
      out.write(".appointments-table {\n");
      out.write("	width: 100%;\n");
      out.write("	border-collapse: separate;\n");
      out.write("	border-spacing: 0;\n");
      out.write("	margin-top: 1rem;\n");
      out.write("	overflow: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".appointments-table thead {\n");
      out.write("	background: linear-gradient(135deg, var(--primary-color) 0%,\n");
      out.write("		var(--info-color) 100%);\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".appointments-table th {\n");
      out.write("	padding: 1rem;\n");
      out.write("	text-align: left;\n");
      out.write("	font-weight: 500;\n");
      out.write("	text-transform: uppercase;\n");
      out.write("	font-size: 0.8rem;\n");
      out.write("	letter-spacing: 0.5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".appointments-table td {\n");
      out.write("	padding: 1rem;\n");
      out.write("	border-bottom: 1px solid rgba(255, 255, 255, 0.05);\n");
      out.write("	vertical-align: middle;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".appointments-table tr:last-child td {\n");
      out.write("	border-bottom: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".appointments-table tr:hover td {\n");
      out.write("	background-color: rgba(255, 255, 255, 0.03);\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Status Badges */\n");
      out.write(".status {\n");
      out.write("	display: inline-block;\n");
      out.write("	padding: 0.3rem 0.6rem;\n");
      out.write("	border-radius: 20px;\n");
      out.write("	font-size: 0.8rem;\n");
      out.write("	font-weight: 600;\n");
      out.write("	text-transform: capitalize;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".status-scheduled {\n");
      out.write("	background-color: rgba(253, 203, 110, 0.2);\n");
      out.write("	color: var(--warning-color);\n");
      out.write("	border: 1px solid var(--warning-color);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".status-completed {\n");
      out.write("	background-color: rgba(0, 184, 148, 0.2);\n");
      out.write("	color: var(--success-color);\n");
      out.write("	border: 1px solid var(--success-color);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".status-cancelled {\n");
      out.write("	background-color: rgba(214, 48, 49, 0.2);\n");
      out.write("	color: var(--danger-color);\n");
      out.write("	border: 1px solid var(--danger-color);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".status-pending {\n");
      out.write("	background-color: rgba(155, 89, 182, 0.2);\n");
      out.write("	color: #9b59b6;\n");
      out.write("	border: 1px solid #9b59b6;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Button Styles */\n");
      out.write(".action-btn {\n");
      out.write("	padding: 0.5rem 1rem;\n");
      out.write("	border: none;\n");
      out.write("	border-radius: 6px;\n");
      out.write("	cursor: pointer;\n");
      out.write("	font-size: 0.8rem;\n");
      out.write("	font-weight: 500;\n");
      out.write("	margin-right: 0.5rem;\n");
      out.write("	transition: all 0.3s ease;\n");
      out.write("	display: inline-flex;\n");
      out.write("	align-items: center;\n");
      out.write("	gap: 0.3rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".action-btn:hover {\n");
      out.write("	transform: translateY(-2px);\n");
      out.write("	box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".complete-btn {\n");
      out.write("	background-color: var(--success-color);\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".complete-btn::before {\n");
      out.write("	content: \"✓\";\n");
      out.write("}\n");
      out.write("\n");
      out.write(".cancel-btn {\n");
      out.write("	background-color: var(--danger-color);\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".cancel-btn::before {\n");
      out.write("	content: \"✕\";\n");
      out.write("}\n");
      out.write("\n");
      out.write(".add-record-btn {\n");
      out.write("	background-color: var(--accent-color);\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".add-record-btn::before {\n");
      out.write("	content: \"➕\";\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logout-btn {\n");
      out.write("	background-color: var(--danger-color);\n");
      out.write("	color: white;\n");
      out.write("	border: none;\n");
      out.write("	padding: 0.5rem 1rem;\n");
      out.write("	border-radius: 6px;\n");
      out.write("	cursor: pointer;\n");
      out.write("	font-size: 0.9rem;\n");
      out.write("	transition: all 0.3s ease;\n");
      out.write("	display: flex;\n");
      out.write("	align-items: center;\n");
      out.write("	gap: 0.3rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logout-btn:hover {\n");
      out.write("	background-color: #c0392b;\n");
      out.write("	transform: translateY(-2px);\n");
      out.write("	box-shadow: 0 4px 8px rgba(214, 48, 49, 0.3);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logout-btn::before {\n");
      out.write("	content: \"🚪\";\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Messages */\n");
      out.write(".message {\n");
      out.write("	padding: 1rem;\n");
      out.write("	margin-bottom: 1.5rem;\n");
      out.write("	border-radius: 8px;\n");
      out.write("	color: white;\n");
      out.write("	display: flex;\n");
      out.write("	align-items: center;\n");
      out.write("	gap: 0.5rem;\n");
      out.write("	animation: fadeIn 0.5s ease;\n");
      out.write("	box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".message::before {\n");
      out.write("	font-size: 1.2rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".message-success {\n");
      out.write("	background-color: var(--success-color);\n");
      out.write("	border-left: 5px solid darken(var(--success-color), 10%);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".message-success::before {\n");
      out.write("	content: \"✅\";\n");
      out.write("}\n");
      out.write("\n");
      out.write(".message-error {\n");
      out.write("	background-color: var(--danger-color);\n");
      out.write("	border-left: 5px solid darken(var(--danger-color), 10%);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".message-error::before {\n");
      out.write("	content: \"❌\";\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Footer */\n");
      out.write(".footer {\n");
      out.write("	background-color: var(--footer-bg);\n");
      out.write("	padding: 1.5rem 2rem;\n");
      out.write("	text-align: center;\n");
      out.write("	font-size: 0.8rem;\n");
      out.write("	color: rgba(255, 255, 255, 0.6);\n");
      out.write("	border-top: 1px solid rgba(255, 255, 255, 0.1);\n");
      out.write("	margin-top: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-links {\n");
      out.write("	display: flex;\n");
      out.write("	justify-content: center;\n");
      out.write("	gap: 1.5rem;\n");
      out.write("	margin-bottom: 0.5rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-link {\n");
      out.write("	color: var(--secondary-color);\n");
      out.write("	text-decoration: none;\n");
      out.write("	transition: color 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-link:hover {\n");
      out.write("	color: var(--accent-color);\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Animations */\n");
      out.write("@\n");
      out.write("keyframes fadeIn {from { opacity:0;\n");
      out.write("	transform: translateY(-10px);\n");
      out.write("}\n");
      out.write("\n");
      out.write("to {\n");
      out.write("	opacity: 1;\n");
      out.write("	transform: translateY(0);\n");
      out.write("}\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Responsive Design */\n");
      out.write("@media ( max-width : 1024px) {\n");
      out.write("	.main-container {\n");
      out.write("		flex-direction: column;\n");
      out.write("	}\n");
      out.write("	.sidebar {\n");
      out.write("		width: 100%;\n");
      out.write("		padding: 1rem;\n");
      out.write("	}\n");
      out.write("	.quick-stats {\n");
      out.write("		display: flex;\n");
      out.write("		gap: 1rem;\n");
      out.write("		justify-content: space-around;\n");
      out.write("	}\n");
      out.write("	.stat-item {\n");
      out.write("		flex-direction: column;\n");
      out.write("		align-items: center;\n");
      out.write("		margin-bottom: 0;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media ( max-width : 768px) {\n");
      out.write("	.header {\n");
      out.write("		flex-direction: column;\n");
      out.write("		gap: 1rem;\n");
      out.write("		padding: 1rem;\n");
      out.write("	}\n");
      out.write("	.nav-bar {\n");
      out.write("		overflow-x: auto;\n");
      out.write("		padding: 0.5rem 1rem;\n");
      out.write("	}\n");
      out.write("	.appointments-table {\n");
      out.write("		display: block;\n");
      out.write("		overflow-x: auto;\n");
      out.write("	}\n");
      out.write("	.card-header {\n");
      out.write("		flex-direction: column;\n");
      out.write("		align-items: flex-start;\n");
      out.write("		gap: 1rem;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Specialization Tag */\n");
      out.write(".specialization {\n");
      out.write("	display: inline-block;\n");
      out.write("	padding: 0.3rem 0.6rem;\n");
      out.write("	background-color: rgba(106, 176, 76, 0.1);\n");
      out.write("	color: #6ab04c;\n");
      out.write("	border-radius: 4px;\n");
      out.write("	font-size: 0.8rem;\n");
      out.write("	font-weight: 500;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Form Styles */\n");
      out.write(".form-inline {\n");
      out.write("	display: inline;\n");
      out.write("	margin: 0;\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Time Badge */\n");
      out.write(".time-badge {\n");
      out.write("	display: inline-block;\n");
      out.write("	padding: 0.3rem 0.6rem;\n");
      out.write("	background-color: rgba(155, 89, 182, 0.1);\n");
      out.write("	color: var(--accent-color);\n");
      out.write("	border-radius: 4px;\n");
      out.write("	font-size: 0.8rem;\n");
      out.write("	font-weight: 500;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- Header -->\n");
      out.write("	<header class=\"header\">\n");
      out.write("		<h1 class=\"header-title\">HealthCare Doctor Portal</h1>\n");
      out.write("		<div class=\"user-info\">\n");
      out.write("			<span class=\"user-greeting\">Welcome,</span> <span class=\"username\">Dr.\n");
      out.write("				");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.username}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("			<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\"\n");
      out.write("				method=\"post\" class=\"form-inline\">\n");
      out.write("				<button type=\"submit\" class=\"logout-btn\">Logout</button>\n");
      out.write("			</form>\n");
      out.write("		</div>\n");
      out.write("	</header>\n");
      out.write("\n");
      out.write("	<!-- Navigation Bar -->\n");
      out.write("	<nav class=\"nav-bar\">\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/DashboardServlet\"\n");
      out.write("			class=\"nav-link ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activePage == 'dashboard' ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("			Dashboard </a> <a\n");
      out.write("			href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/DoctorAppointmentsServlet\"\n");
      out.write("			class=\"nav-link ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activePage == 'appointments' ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("			Appointments </a> <a\n");
      out.write("			href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/PatientRecordsServlet\"\n");
      out.write("			class=\"nav-link ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activePage == 'records' ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("			Patient Records </a> <a\n");
      out.write("			href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/DoctorScheduleServlet\"\n");
      out.write("			class=\"nav-link ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activePage == 'schedule' ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("			Schedule </a>\n");
      out.write("	</nav>\n");
      out.write("\n");
      out.write("	<div class=\"main-container\">\n");
      out.write("		<!-- Sidebar -->\n");
      out.write("		<aside class=\"sidebar\">\n");
      out.write("			<div class=\"sidebar-header\">\n");
      out.write("				<h2 class=\"sidebar-title\">Doctor Panel</h2>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"quick-stats\">\n");
      out.write("				<div class=\"stat-item\">\n");
      out.write("					<span>Today's Appointments:</span> <span class=\"stat-value\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${todaysAppointments}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"stat-item\">\n");
      out.write("					<span>Pending Requests:</span> <span class=\"stat-value\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pendingAppointmentsCount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"stat-item\">\n");
      out.write("					<span>Available Slots:</span> <span class=\"stat-value\">8</span>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div style=\"padding: 0 1.5rem; margin-top: auto;\">\n");
      out.write("				<div\n");
      out.write("					style=\"background: rgba(255, 255, 255, 0.05); padding: 1rem; border-radius: 8px;\">\n");
      out.write("					<p\n");
      out.write("						style=\"font-size: 0.8rem; margin-bottom: 0.5rem; color: var(--secondary-color);\">Quick\n");
      out.write("						Actions</p>\n");
      out.write("					<button class=\"action-btn complete-btn\"\n");
      out.write("						style=\"width: 100%; justify-content: center; margin-bottom: 0.5rem;\">Complete\n");
      out.write("						All</button>\n");
      out.write("					<button class=\"action-btn cancel-btn\"\n");
      out.write("						style=\"width: 100%; justify-content: center;\">Cancel All</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</aside>\n");
      out.write("\n");
      out.write("		<!-- Main Content -->\n");
      out.write("		<main class=\"main-content\">\n");
      out.write("			<!-- Display messages -->\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("			<!-- Pending Appointments Card -->\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("			<!-- Scheduled Appointments Card -->\n");
      out.write("			<div class=\"card appointments-card\">\n");
      out.write("				<div class=\"card-header\">\n");
      out.write("					<h3 class=\"card-title\">Scheduled Appointments</h3>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"card-body\">\n");
      out.write("					<table class=\"appointments-table\">\n");
      out.write("						<thead>\n");
      out.write("							<tr>\n");
      out.write("								<th>Date</th>\n");
      out.write("								<th>Time</th>\n");
      out.write("								<th>Patient</th>\n");
      out.write("								<th>Phone</th>\n");
      out.write("								<th>Status</th>\n");
      out.write("								<th>Actions</th>\n");
      out.write("							</tr>\n");
      out.write("						</thead>\n");
      out.write("						<tbody>\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("						</tbody>\n");
      out.write("					</table>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</main>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<!-- Footer -->\n");
      out.write("	<footer class=\"footer\">\n");
      out.write("		<div class=\"footer-links\">\n");
      out.write("			<a href=\"#\" class=\"footer-link\">Privacy Policy</a> <a href=\"#\"\n");
      out.write("				class=\"footer-link\">Terms of Service</a> <a href=\"#\"\n");
      out.write("				class=\"footer-link\">Support</a> <a href=\"#\" class=\"footer-link\">Contact\n");
      out.write("				Us</a>\n");
      out.write("		</div>\n");
      out.write("		<p>© 2023 MediCare Doctor Portal. All rights reserved.</p>\n");
      out.write("	</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /view/doctorAppointments.jsp(611,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty message}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("				<div class=\"message message-success\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /view/doctorAppointments.jsp(614,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty error}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("				<div class=\"message message-error\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /view/doctorAppointments.jsp(619,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty pendingAppointments}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("				<div class=\"card pending-appointments-card\">\n");
          out.write("					<div class=\"card-header\">\n");
          out.write("						<h3 class=\"card-title\">Pending Appointment Requests</h3>\n");
          out.write("					</div>\n");
          out.write("\n");
          out.write("					<div class=\"card-body\">\n");
          out.write("						<table class=\"appointments-table\">\n");
          out.write("							<thead>\n");
          out.write("								<tr>\n");
          out.write("									<th>Date</th>\n");
          out.write("									<th>Time</th>\n");
          out.write("									<th>Patient</th>\n");
          out.write("									<th>Phone</th>\n");
          out.write("									<th>Actions</th>\n");
          out.write("								</tr>\n");
          out.write("							</thead>\n");
          out.write("							<tbody>\n");
          out.write("								<!-- In doctorAppointments.jsp -->\n");
          out.write("								");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("							</tbody>\n");
          out.write("						</table>\n");
          out.write("					</div>\n");
          out.write("				</div>\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /view/doctorAppointments.jsp(638,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("appointment");
      // /view/doctorAppointments.jsp(638,8) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/view/doctorAppointments.jsp(638,8) '${pendingAppointments}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pendingAppointments}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("									<tr>\n");
            out.write("										<td>");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\n");
            out.write("										<td><span class=\"time-badge\">");
            if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</span></td>\n");
            out.write("										<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.patientName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("										<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.patientPhone}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("										<td>\n");
            out.write("											<form\n");
            out.write("												action=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/ManageAppointmentServlet\"\n");
            out.write("												method=\"post\" class=\"form-inline\">\n");
            out.write("												<input type=\"hidden\" name=\"appointmentId\"\n");
            out.write("													value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.appointmentId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> <input\n");
            out.write("													type=\"hidden\" name=\"action\" value=\"scheduled\">\n");
            out.write("												<button type=\"submit\" class=\"action-btn complete-btn\">Accept</button>\n");
            out.write("											</form>\n");
            out.write("											\n");
            out.write("											<form\n");
            out.write("												action=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/ManageAppointmentServlet\"\n");
            out.write("												method=\"post\" class=\"form-inline\">\n");
            out.write("												<input type=\"hidden\" name=\"appointmentId\"\n");
            out.write("													value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.appointmentId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> <input\n");
            out.write("													type=\"hidden\" name=\"action\" value=\"rejected\">\n");
            out.write("												<button type=\"submit\" class=\"action-btn cancel-btn\">Reject</button>\n");
            out.write("											</form>\n");
            out.write("										</td>\n");
            out.write("									</tr>\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /view/doctorAppointments.jsp(640,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.date}", java.util.Date.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /view/doctorAppointments.jsp(640,14) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /view/doctorAppointments.jsp(642,39) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.time}", java.util.Date.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /view/doctorAppointments.jsp(642,39) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setPattern("hh:mm a");
      int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
      _jspx_th_fmt_005fformatDate_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /view/doctorAppointments.jsp(692,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("appointment");
      // /view/doctorAppointments.jsp(692,7) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/view/doctorAppointments.jsp(692,7) '${scheduledAppointments}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${scheduledAppointments}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("								<tr>\n");
            out.write("									<td>");
            if (_jspx_meth_fmt_005fformatDate_005f2(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("</td>\n");
            out.write("									<td><span class=\"time-badge\">");
            if (_jspx_meth_fmt_005fformatDate_005f3(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("</span></td>\n");
            out.write("									<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.patientName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("									<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.patientPhone}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("									<td><span\n");
            out.write("										class=\"status status-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.status.toLowerCase()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("											");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.status}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </span></td>\n");
            out.write("									<td>");
            if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\n");
            out.write("										<form\n");
            out.write("											action=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/view/addMedicalRecord.jsp\"\n");
            out.write("											method=\"get\" class=\"form-inline\">\n");
            out.write("											<input type=\"hidden\" name=\"appointmentId\"\n");
            out.write("												value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.appointmentId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> <input\n");
            out.write("												type=\"hidden\" name=\"patientId\"\n");
            out.write("												value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.patientId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("											<button type=\"submit\" class=\"action-btn add-record-btn\">Add\n");
            out.write("												Record</button>\n");
            out.write("										</form></td>\n");
            out.write("								</tr>\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f2_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f2.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /view/doctorAppointments.jsp(694,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f2.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.date}", java.util.Date.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /view/doctorAppointments.jsp(694,13) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f2.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f2 = _jspx_th_fmt_005fformatDate_005f2.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f2);
      _jspx_th_fmt_005fformatDate_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f3(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f3_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f3.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f3.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /view/doctorAppointments.jsp(696,38) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f3.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.time}", java.util.Date.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /view/doctorAppointments.jsp(696,38) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f3.setPattern("hh:mm a");
      int _jspx_eval_fmt_005fformatDate_005f3 = _jspx_th_fmt_005fformatDate_005f3.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f3);
      _jspx_th_fmt_005fformatDate_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f3, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /view/doctorAppointments.jsp(703,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.status == 'SCHEDULED'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("											<form\n");
          out.write("												action=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/UpdateAppointmentStatusServlet\"\n");
          out.write("												method=\"post\" class=\"form-inline\">\n");
          out.write("												<input type=\"hidden\" name=\"appointmentId\"\n");
          out.write("													value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.appointmentId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"> <input\n");
          out.write("													type=\"hidden\" name=\"status\" value=\"COMPLETED\">\n");
          out.write("												<button type=\"submit\" class=\"action-btn complete-btn\">Complete</button>\n");
          out.write("											</form>\n");
          out.write("											<form\n");
          out.write("												action=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/UpdateAppointmentStatusServlet\"\n");
          out.write("												method=\"post\" class=\"form-inline\">\n");
          out.write("												<input type=\"hidden\" name=\"appointmentId\"\n");
          out.write("													value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appointment.appointmentId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"> <input\n");
          out.write("													type=\"hidden\" name=\"status\" value=\"CANCELLED\">\n");
          out.write("												<button type=\"submit\" class=\"action-btn cancel-btn\">Cancel</button>\n");
          out.write("											</form>\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
